### PR TITLE
[Bug 1083423] Add auto-follow and follow APIs to questions and answers.

### PR DESCRIPTION
**Pull request by mythmon**
This makes users automatically follow questions they ask, answers the give, and the questions they answer. 

It also adds APIs for users to manually follow and unfollow questions and answers.

r?

### CODE REVIEW

**Comment by rlr** [comment]
some tests are failing :point_up:

**Comment by rlr** [comment]
oh yeah. those fails make sense since you are doing auto-following now. More notifications are created by the tests

**Comment by mythmon** [comment]
Gah. I only tested the tests I added.

**Comment by mythmon** [comment]
That should fix it.

**Comment by rlr** [comment]
They passed locally. some weird ES errors on travis. restarted them

**Comment by rlr** [comment]
r+ once travis is happyyyy

**Pull request merged**
