### PR TITLE
Fix issues with in_review.py

### PR DESCRIPTION
**Pull request by willkg**
* off-by-one with to_date
* using git-log with a range when we should be using git-show

r?

### CODE REVIEW

**Comment by mythmon** [comment]
LGTM. r+

By the way, I'm getting this error both on this branch and on master. It happens right after the "Everyone" header gets printed out.

```traceback
Traceback (most recent call last):
  File "./scripts/in_review.py", line 356, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./scripts/in_review.py", line 352, in main
    print_all_people()
  File "./scripts/in_review.py", line 294, in print_all_people
    people = sorted(all_people, key=lambda a: a.decode('utf-8').lower())
  File "./scripts/in_review.py", line 294, in <lambda>
    people = sorted(all_people, key=lambda a: a.decode('utf-8').lower())
  File "/home/mythmon/src/kitsune/venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by willkg** [comment]
Hrm... I thought I fixed this, but maybe I did it wrong. I'll look into it.

**Comment by willkg** [comment]
^^^ That fixes the total crap that was str/unicode handling in the code. Sorry.

**Comment by mythmon** [comment]
Now the script runs to completion without error. Thanks!

**Pull request merged**
