### PR TITLE
[Bug 1178894] Font color missing in Interval field on Support Forum Metrics page

### PR DESCRIPTION
**Pull request by orvi2014**

### CODE REVIEW

**Comment by mythmon** [comment]
You shouldn't edit this file, since it is a "library" css file (though, admittedly misplaced). You should make a change like this one in [`rickshaw.sumo.less`](https://github.com/mozilla/kitsune/blob/40f3bc790594fd26f318e667d1cd953faf58eb90/kitsune/sumo/static/sumo/less/rickshaw.sumo.less) which is where we have customized Rickshaw's styling.

**Comment by orvi2014** [comment]
Hey, I update the PR. Would you test it please ?

**Comment by orvi2014** [comment]
I update the PR title according to BUG title.

**Comment by mythmon** [comment]
Looks good, thank you!

Sorry it took so long to get to reviewing this.

**Comment by orvi2014** [comment]
Ah its okay. I was tensed though . Anyway, thanks :)

**Pull request merged**
