### PR TITLE
Revert "Disable sentry in prod due to issues caused by increased IO"

### PR DESCRIPTION
**Pull request by akatsoulas**
Reverts mozilla/kitsune#3497

### CODE REVIEW

**Comment by akatsoulas** [comment]
@jgmize @metadave thoughts on this?

**Comment by metadave** [comment]
have performance issues with Sentry logging been addressed?

**Comment by jgmize** [comment]
How about we play it safe and only enable it in oregon-a initially, leaving it off in oregon-b for (say) a couple of weeks?

**Comment by metadave** [comment]
+1

by any chance are there any flags we can use to throttle communications w/ sentry?

**Comment by akatsoulas** [comment]
@metadave let me check this

**Comment by akatsoulas** [comment]
Following up on the last comment from @metadave, we can rate limit sentry under settings [0]. I tried looking into that but it looks like that I cannot access these settings. Is there an admin level access that can tweak these settings?
https://docs.sentry.io/accounts/quotas/#id1

**Comment by jgmize** [comment]
We could only enable sentry in one of the active production clusters, cutting the potential volume in half, and in the event of running into IO bottlenecks due to sentry volume, it should only affect one cluster and the traffic will fail over to the other automatically at the ELB.

**Comment by akatsoulas** [comment]
Closing this. Sentry is enabled only in one of the clusters in the new infra.

**Pull request closed without merging**
