### PR TITLE
Remove no-doodle variant of the switching devices wizard.

### PR DESCRIPTION
**Pull request by mikeconley**
Fixes mozilla/sumo#1504.

### CODE REVIEW

**Comment by hannajones** [comment]
This all looks good, but I'm curious if we also want to remove the script tag that loads waffle.js: https://github.com/mozilla/kitsune/blob/main/kitsune/sumo/jinja2/base.html#L341

IIRC the doodle was the only use case for waffle.js and I had to add that in when doing the initial doodle work. If we're not using waffle for anything else it seems worth removing it again.

**Comment by mikeconley** [comment]
> This all looks good, but I'm curious if we also want to remove the script tag that loads waffle.js: https://github.com/mozilla/kitsune/blob/main/kitsune/sumo/jinja2/base.html#L341

Good catch! Removed that too in the latest update.

**Review by hannajones — APPROVED** [review]
LGTM thanks!

**Comment by mikeconley** [comment]
Thanks!

**Pull request merged**
