### PR TITLE
Add Yelp's pre-commit.

### PR DESCRIPTION
**Pull request by mythmon**
@rehandalal r?

### CODE REVIEW

**Comment by mythmon** [comment]
To add the eslint linter, add this to `.pre-commit-config.yaml`.

```
-   repo: http://github.com/pre-commit/mirrors-eslint
    sha: 62596a0b5f83171fdf99c575a1b5efd45b3abe5b
    hooks:
    -   id: eslint
        files: \.jsx?
```

**Comment by rehandalal** [comment]
might be nice to have some docs?

**Comment by mythmon** [comment]
I lied, and didn't wait until tomorrow. I added docs tonight.

**Comment by edmorley** [comment]
Updating to virtualenv 12.1.1 is the cause of https://github.com/erikrose/peep/issues/82 fwiw

**Comment by edmorley** [comment]
Updating to virtualenv 12.1.1 is the cause of https://github.com/erikrose/peep/issues/82 fwiw (CC @rlr)

**Comment by edmorley** [comment]
Although that said, the Vagrant provision script installs virtualenv without pinning a version, so this would happen anyway:
https://github.com/mozilla/kitsune/blob/4d3c420a06f74a9542a260737f196e7fa46f5107/bin/vagrant_provision.sh#L36

**Comment by willkg** [comment]
@edmorley the vagrant provision script isn't used, yet.

**Pull request merged**
