### PR TITLE
[bug 1133093] Select avatar size for user API

### PR DESCRIPTION
**Pull request by rehandalal**
tiny r?

### CODE REVIEW

**Comment by mythmon** [comment]
I thought you said this wouldn't work?

Is there an easy way to test this? Does the gravatar url change much, or would the only way to tell be to download the image and look at it? If it is easy, it would be nice to have tests for this so refactoring is easier in the future.

**Comment by rehandalal** [comment]
I originally had issues because I was using `getattr` but context is a dict, so that was silly.

I'll add tests. This changes the `?s={size}` in the URL.

**Comment by rehandalal** [comment]
test included ^

**Comment by mythmon** [comment]
Nice.

**Pull request merged**
