### PR TITLE
[bug 1098469] Added original asker to question list.

### PR DESCRIPTION
**Pull request by rlr**
Also added solver for consistency.
r?

BTW, I wonder if using username instead of display_name is a bug?

### CODE REVIEW

**Comment by mythmon** [comment]
I think it is a bug. We should use display name here.

**Comment by rehandalal** [comment]
+1 on display name

**Comment by rlr** [comment]
fixord to display_name :point_up:

**Comment by rlr** [comment]
oops i broke something here

**Comment by rlr** [comment]
travis is all smiley again :smiley:

**Comment by rehandalal** [comment]
lgtm. r+

**Comment by rlr** [comment]
9a8d65177a4ca63dd6bf227388295ff6610d08a6 [bug 1098469] Added original asker to question list.

**Pull request closed without merging**
