### PR TITLE
Fix group avatar upload for s3 storage

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
This didn't appear to work. Replaced by https://github.com/mozilla/kitsune/commit/d0564a90ad0a6a7f6ffb06f70129029ff4565b14

**Comment by pmac** [comment]
Yeah... sorry. Was pushing here to get circle to test it. Thanks for the assist.

**Comment by glogiotatidis** [comment]
np, i'm glad we got this out of the way :)

**Comment by safwanrahman** [comment]
> This didn't appear to work. Replaced by d0564a9

@glogiotatidis Which PR included thia commit?

**Pull request closed without merging**
