### PR TITLE
[bug 1058731] Don't send review email to non reviewers

### PR DESCRIPTION
**Pull request by rehandalal**
r?

### CODE REVIEW

**Comment by mythmon** [comment]
Travis failures here are test failures not just lint.

**Comment by rehandalal** [comment]
rebased

**Comment by mythmon** [comment]
```
FAIL: kitsune/wiki/tests/test_templates.py:NewRevisionTests.test_new_revision_POST_document_with_current
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/mozilla/kitsune/kitsune/wiki/tests/test_templates.py", line 870, in test_new_revision_POST_document_with_current
    eq_(2, len(mail.outbox))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: 2 != 1
```

**Comment by rehandalal** [comment]
test fixed and updated to test this PR ^

**Comment by mythmon** [comment]
r+

**Pull request merged**
