### PR TITLE
[Bug 969182] Update deploy script to use Python 2.7.

### PR DESCRIPTION
**Pull request by mythmon**
This requires IT work to deploy onto stage and prod, but Dev is running this happily.

f?

TODO

* [x] It works (I think)
* [x] Test it harder (especially on stage)
* [x] Make Travis run 2.7. (#2314)

### CODE REVIEW

**Comment by rlr** [comment]
I don't see anything obviously wrong here. I guess we just need to try it on stage?

**Comment by mythmon** [comment]
^ Rebased on to current master, which has Travis 2.7 stuff.

**Comment by mythmon** [comment]
Yeah, pretty much. It worked on dev, I just wanted to get another set of eyes on it before I moved forward.

**Comment by mythmon** [comment]
I think this worked on stage over the weekend. I think we are ready to go to prod with this.

r?

**Comment by rlr** [comment]
yay! :ship:

**Comment by mythmon** [comment]
I talked to jakem. He says he should have time to work on this tomorrow or Thursday. We'll need to do some interesting things to get it to deploy right. For that reason, I'm not going to merge this until we are ready to deploy. But we're all ready!

**Comment by mythmon** [comment]
25d7434 [Bug 969182] Update deploy script to use Python 2.7

**Pull request closed without merging**
