### PR TITLE
Fix Bug 1416886 - Update Download Firefox Icon

### PR DESCRIPTION
**Pull request by bensternthal**
Due to some issues with my local docker install I could not test this locally. Can you deploy to stage so I can test? After that we should be good to go.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Almost there! https://screenshots.firefox.com/v4xHHs8Cmr4sIY0k/support.allizom.org

**Comment by bensternthal** [comment]
Ugh. OK let me tweak.

Also let me see if I can get the docker install running again locally so I can avoid having you manually check.

**Comment by bensternthal** [comment]
Was able to get docker running so I could tweak. This version should be OK but please double check.

**Comment by glogiotatidis** [comment]
Yap, looks good. Thanks! 🍺

**Pull request merged**
