### PR TITLE
Update most node dependencies

### PR DESCRIPTION
**Pull request by escattone**
mozilla/sumo#1179

This PR updates all of our Node.js dependencies to their latest versions except the following (which will be addressed via separate issues):

- Upgrade `@mozilla-protocol/core` to `16` ([changelog](https://github.com/mozilla/protocol/blob/main/CHANGELOG.md)) --> https://github.com/mozilla/sumo/issues/1182
- Upgrade `codemirror` to version `6` ([migration guide](https://codemirror.net/docs/migration/)) --> https://github.com/mozilla/sumo/issues/1183
- Upgrade `d3` to version `7` ([changelog](https://github.com/d3/d3/blob/main/CHANGES.md)) --> https://github.com/mozilla/sumo/issues/1184
- Removal of `react` dependency from tests --> https://github.com/mozilla/sumo/issues/1185

With this PR, here's what `npm outdated` returns:
```
repos/kitsune % npm outdated
Package                 Current   Wanted  Latest  Location                             Depended by
@mozilla-protocol/core   10.0.1   10.0.1  16.0.1  node_modules/@mozilla-protocol/core  kitsune
codemirror              5.65.11  5.65.11   6.0.1  node_modules/codemirror              kitsune
d3                       3.5.17   3.5.17   7.8.2  node_modules/d3                      kitsune
react                    0.13.3   0.13.3  18.2.0  node_modules/react                   kitsune
```

### CODE REVIEW

**Comment by escattone** [comment]
The fix I added to `webpack/asset-json-plugin.js` is due to an update in `webpack` that (for some unknown reason) changed the `thisCompilation` web-hook such that it sometimes provides an absolute rather than relative path for an asset's `sourceFilename`. The fix ensures that we're always working with relative paths.

I've verified that the fix creates the exact same `source-to-asset.json` file that's created without this update to webpack.

**Comment by akatsoulas** [comment]
@escattone is this good for a review? It also needs a rebase

**Comment by escattone** [comment]
@akatsoulas Yes, it's ready for review. I started on the rebase last Friday, but it's a painful one. I'll get that done today.

**Comment by escattone** [comment]
Latest result of `npm outdated`:
```
kitsune@bb33faa3b099:~$ npm outdated
Package                 Current   Wanted  Latest  Location                             Depended by
@mozilla-protocol/core   10.0.1   10.0.1  16.0.1  node_modules/@mozilla-protocol/core  app
codemirror              5.65.11  5.65.11   6.0.1  node_modules/codemirror              app
d3                       3.5.17   3.5.17   7.8.2  node_modules/d3                      app
```

**Review by akatsoulas — APPROVED** [review]

**Pull request merged**
