### PR TITLE
[Bug 1260817] Show Save as draft button also under translated article content preview

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
The lint test failed, can you please restart it? Other tests passed - r?

**Comment by mythmon** [comment]
@safwanrahman can you review this?

**Comment by safwanrahman** [comment]
r+ from my end.
@mythmon can merge?

**Comment by mythmon** [comment]
Tests pass, @safwanrahman likes it. I'll merge this.

**Pull request merged**
