### PR TITLE
[Bug 1261896] Show community support link for all products and locales - reopened

### PR DESCRIPTION
**Pull request by MikkCZ**
This is reopened PR #2839. @safwanrahman can I ask you for a re-review?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Hey folks, Kitsune is still in code freeze mode. I'm happy to bring in some **very** basic stuff that can make your life easier what would be template related like #2890 but not anything more complicated. This one is on the fence b/c it adds code. 

I'll keep this open for now but when time permits I can revisit.

**Comment by akatsoulas** [comment]
@MikkCZ that would be me. I can start going through this PR in the next couple of days. 

Regarding the rest of the PRs, I will work with @madasan to start prioritizing and adding them into our sprints. Probably it would be helpful for us to know which are the more urgent in order to prioritize accordingly (maybe through an issue)

**Comment by MikkCZ** [comment]
Thank you. Will you prioritize based on tickets in Bugzilla or issue here on Github? I can file an issue here for the PRs of course (I should updated them as there are some conflicts too).

**Comment by akatsoulas** [comment]
An issue can help us focus on the more "urgent" ones. Otherwise we will process them through the tickets in Bugzilla.

**Comment by MikkCZ** [comment]
This PR is stale for too long, so I am closing this. The history should be preserved, so if anyone want's to update it or use as inspiration, feel free to.

**Pull request closed without merging**
