### PR TITLE
[Bug 1150382] Add placeholders indicating valid date input format for new announcements

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
r?

**Comment by safwanrahman** [comment]
I think a datepicker was added there? 
https://bugzilla.mozilla.org/show_bug.cgi?id=1083914

**Comment by MikkCZ** [comment]
True. I thought the reported would like to see the time format in case it's pasted manually. But in case the data picker was added after the report, we might close this and the bug as well.

**Comment by safwanrahman** [comment]
I think so. Because, the bug was filled before we added the date Picker.
So better to close the bug!

**Comment by MikkCZ** [comment]
I should definitely go through the whole list or support.mozilla.org bugs and check, what's hidden there.

Closed the bug as duplicate and closing this PR too. Thank you for noticing a finding the original bug.

**Pull request closed without merging**
