### PR TITLE
transferred contents of sumo-tests repo

### PR DESCRIPTION
**Pull request by rbillings**
Moved all desktop and mobile tests along with supporting pages and config files.

### CODE REVIEW

**Comment by rbillings** [comment]
@mythmon - r+?

**Comment by safwanrahman** [comment]
@rbillings We do run Smoketests in Travis with xvfb. It seems that the test is failing. You should make proper changes in the tests that it pass in the developing server.

**Comment by safwanrahman** [comment]
What I was going to do, is as following
* Change in the script [here] (https://github.com/mozilla/kitsune/blob/master/scripts/travis/smoketests.sh) Which runs the Smoketests in Travis ci
* Make a python script to create a user and a super user. And store the usernames and passwords in ``variables.json``
* Run the python script with the ``smoketests.sh`` script in the Django shell so it will create a ``variables.json`` file in appropriate directory
* Change [this command](https://github.com/mozilla/kitsune/blob/master/scripts/travis/smoketests.sh#L16) with the appropriate command with the path of script. ``eg:py.test --driver=firefox --destructive --variables=/full/path/to/variables.json``

**Comment by safwanrahman** [comment]
I have done most of the thing in commit [c07178](https://github.com/mozilla/kitsune/commit/93e1324c47572656085569ab5236b777c4c07178). So the Travis is running the smoketests as it should be. But there are some issue from Kitsune end. Need to figure out with @mythmon in order to fix them.

**Comment by mythmon** [comment]
@rbillings this PR is over 6 weeks old now without any activity. I'm going to close it now to keep things tidy. If you make more progress here, please re-open this PR and add your changes. If you need anything getting this going, I'd be happy to help.

**Pull request closed without merging**
