### PR TITLE
Announcements, CustomerCare, Dashboard: Functional timezone in sync w…

### PR DESCRIPTION
**Pull request by omkar-dsd**
In Accordance to [Django Documentation](https://docs.djangoproject.com/en/1.8/ref/utils/#module-django.utils.timezone), syncing the timezone with the one in Django's settings.

### CODE REVIEW

**Comment by omkar-dsd** [comment]
#3412

**Comment by pmac** [comment]
Hi! My apologies for the delay in response. This does look good, but I'm going to have to research the implications a bit more. I'm afraid that changing what that field means at this point would make using it with the existing data confusing without also converting all of that existing data.

**Comment by omkar-dsd** [comment]
@pmac DateTimeField is timezone aware, might not cause any issue. Still, to be on a safer side, I will also go through the related consequences, if any.

**Comment by omkar-dsd** [comment]
@pmac any update on this ?

**Comment by akatsoulas** [comment]
Thank  you @omkar-dsd for this PR. Indeed this is a desired change but as Pmac mentioned in his last comment this will require to update our current database entries which is not currently possible b/c the project is in the middle of a big upgrade. Thank you again for your contribution.

**Pull request closed without merging**
