### PR TITLE
[Bug 1255056] Make class_selected() safe

### PR DESCRIPTION
**Pull request by MikkCZ**
Would be great if this can be tested each time `class_selected()` is called...

Or do we want to use `class_selected()` or `if {% if %}class="selected"{% endif %}` as [here](https://github.com/mozilla/kitsune/blob/6650c53623127d60b34eedb3808e131dc646b412/kitsune/questions/jinja2/questions/question_list.html#L202)?

### CODE REVIEW

**Comment by MikkCZ** [comment]
Can someone please re-run the tests? Failed on installation.

**Comment by safwanrahman** [comment]
Can you please write a test so that we can avoid it in future?

**Comment by MikkCZ** [comment]
Sure I can write a test for the particular occurrence reported in the bug, but not sure how to do it for all occurrences (will avoid mistakes for current places where used, but not for any future use somewhere else).

**Comment by mythmon** [comment]
There is a better way of doing this. Since the output of `class_selected` is always safe, we can mark it as such in the helper function. That lives in [`kitsune/sumo/templatetags/jinja2_helpers.py`](https://github.com/mozilla/kitsune/blob/master/kitsune/sumo/templatetags/jinja_helpers.py#L468-L476). Wrapping the output of that function in a `Markdown(...)` instance should fix this.

**Comment by MikkCZ** [comment]
Thank you, I will check it tomorrow.

**Comment by mythmon** [comment]
This looks good to me. @safwanrahman, do you still want a test for this? What kind of test do you want?

@homu delegate=safwanrahman

**Comment by safwanrahman** [comment]
So it should test, the class is there and the text is there. I have made a similar kind of test
https://github.com/mozilla/kitsune/pull/2759/files#diff-f96d1b40b0f6f4785dcc421f2c0e35d6R1699

**Comment by MikkCZ** [comment]
Tests committed, by due to the GitHub outage not visible here yet. Hopefully will align itself soon.

**Comment by MikkCZ** [comment]
Force pushed to run the tests. @safwanrahman r?

**Comment by safwanrahman** [comment]
I was hoping to have a test of templates rather than template tags. 
is it possible for you to write the test for template?
Otherwise @mythmon should review the test as I dont have much experience with the jinja2 tags and their tests.

**Comment by MikkCZ** [comment]
The fix was in changing how the filter works, so I wanted to test it. If you think I should test also the template, I will do.

**Comment by MikkCZ** [comment]
Test for the question list added.

**Comment by safwanrahman** [comment]
@homu retry

**Comment by mythmon** [comment]
@homu r+

**Comment by mythmon** [comment]
@MikkCZ it looks like you failed the linter. Just some whitespace issues to fix. You should be able to run these tests locally with `precommit run --all-files`. You can make sure this happens automatically in the future by running `precommit install`.

**Comment by MikkCZ** [comment]
Cool! Fixed now. :)

**Comment by safwanrahman** [comment]
@homu r+

**Pull request merged**
