### PR TITLE
[fix #3354] Improve UX of Thunderbird download button.

### LINKED ISSUE #3354: Fix Thunderbird download button UX
The download button breaks the header copy layout:

https://support.mozilla.org/en-US/products/thunderbird

screen shot 2018-10-03 at 3 58 03 pm

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by pmac** [comment]
I assume this was unintentional, but in the 2nd screenshot the product logo is the placeholder.

**Comment by jpetto** [comment]
> I assume this was unintentional, but in the 2nd screenshot the product logo is the placeholder.

Yeah, I didn't go through the effort of updating all the icons in my local DB. 

@madasan - Please ignore the icon on the left! 😄

**Comment by pmac** [comment]
Also, I see on the firefox page that the download button doesn't include a logo at all. Is there a reason to do so here even though the Thunderbird logo is on the page? Keeping DL buttons consistent on the site seems like a good idea.

**Comment by madasan** [comment]
I vote for standardization all the way especially if it makes things easier.

cc'ing @ryanleesipes, the Thunderbird community manager.

**Comment by jpetto** [comment]
This is now ready for final review!

**Comment by jpetto** [comment]
Screenshot of final implementation:

screen shot 2019-01-08 at 12 59 34 pm

**Pull request merged**
