### PR TITLE
Update wiki document page style for redesign

### PR DESCRIPTION
**Pull request by mlagace**
* Updated the wiki document page style based on the mockup redesign.

image

### CODE REVIEW

**Comment by jpetto** [comment]
@mlagace Can you rebase all of the PRs with conflicts to get more manageable/accurate diffs? Thanks!

**Comment by mlagace** [comment]
Yep I'll rebase all of those PRs @jpetto thanks!

**Comment by jpetto** [comment]
Code-wise this looks okay, but the `<h1 class="wiki-product-title cf">` element is overlapping the search box, making the input effectively inert. Looks like the issue is the `<div>` containing the `<form>` is `float`ing left.

screen shot 2018-06-28 at 4 44 12 pm

**Comment by mlagace** [comment]
This should be fixed now @jpetto.

**Comment by jpetto** [comment]
I think this is all set to go after a rebase. 👍

**Comment by mlagace** [comment]
Rebased

**Pull request merged**
