### PR TITLE
Spelling Mistake in the Document

### PR DESCRIPTION
**Pull request by AdrianCYFu**
There is a spelling error in this document.  The word "provind" should be "providing".  If you have any questions about this mistake, please feel free to contact me.

### CODE REVIEW

**Comment by MikkCZ** [comment]
Is it in docs/searchchapter.rst (https://kitsune.readthedocs.io/en/latest/searchchapter.html)?

**Comment by AdrianCYFu** [comment]
It's in this document:  http://kitsune.readthedocs.io/en/latest/searchchapter.html, so yes it is.

**Comment by MikkCZ** [comment]
This pull request actually does not fix it - it only contains commits in master, which are missing in the auto branch. I will create a new PR for the master branch.

**Comment by MikkCZ** [comment]
This pull request actually does not fix it - it only contains commits in master, which are missing in the auto branch. I will create a new PR for the master branch.

Or do you want to make another pull request fixing the typo in the master branch? You can just open https://github.com/mozilla/kitsune/blob/master/docs/searchchapter.rst, click the edit (pencil) icon and correct the file.

**Comment by AdrianCYFu** [comment]
Thanks for the tip!  
 Phone:  604-836-1438 

    On Monday, May 2, 2016 12:12 PM, Michal Stanke <notifications@github.com> wrote:
 

 This pull request actually does not fix it - it only contains commits in master, which are missing in the auto branch. I will create a new PR for the master branch.Or do you want to make another pull request fixing the typo in the master branch? You can just open https://github.com/mozilla/kitsune/blob/master/docs/searchchapter.rst, click the edit (pencil) icon and correct the file.—

**Comment by MikkCZ** [comment]
You are welcome. :) I see you have already updated the file. For some reason the new pull request did not appeared here yet. You can open it on https://github.com/mozilla/kitsune/compare/master...AdrianCYFu:patch-1?expand=1 and than just close this one.

**Comment by AdrianCYFu** [comment]
Where is the documentation for this page, http://kitsune.readthedocs.io/en/latest/products.html?

**Comment by MikkCZ** [comment]
It's https://kitsune.readthedocs.io/en/latest/searchchapter.html, but the changed won't be visible there until the pull request is closed (merged).

**Pull request closed without merging**
