### PR TITLE
Fix "./manage.py" NameError when "USE_DEBUG_TOOLBAR" is enabled"

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
Actually breaks almost every ./manage.py run.

**Comment by safwanrahman** [comment]
we do not use jingo anymore. 
So this is not a correct way to fix it

**Comment by MikkCZ** [comment]
Thanks, fixed "the best possible way" - deleting. ;)

**Comment by safwanrahman** [comment]
Yap. Since we dont use jinja as a default template loader, so we dont need ``JINGO_EXCLUDE_APPS`` anymore.
:+1: for removing it
r+ from my end

**Comment by MikkCZ** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
r+ Thanks!

**Pull request merged**
