### PR TITLE
Update the test packages to the latest stable versions

### PR DESCRIPTION
**Pull request by davehunt**
A few packages have updates. These are in use for other Web QA suites, and I've tested them locally too. @glogiotatidis r?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Thanks Dave :beers:

**Comment by safwanrahman** [comment]
@glogiotatidis I think, the test should be re run before marging

**Comment by MikkCZ** [comment]
Or automating the merges with @homu, seemed to be an interesting idea. @mythmon might know, if you need to be added somewhere or something.

**Comment by glogiotatidis** [comment]
Since this was just package upgrades and Dave tested it locally beforehand I didn't pay attention to travis but I should. Thanks @safwanrahman

**Comment by mythmon** [comment]
@glogiotatidis [homu](http://homu.io/) would deal with any sort of merge testing, if you want. You'd have to use it for all commits for it to actually work (it gets grumpy when other people touch master). You can approve a PR by saying `@homu r+`. It will run the tests merged with master, and then merge the code, making sure that tests always pass on master. I found it quite useful.

**Pull request merged**
