### PR TITLE
[Bug 1133326] Cleanup survey code, and add Firefox refresh survey

### PR DESCRIPTION
**Pull request by mythmon**
To test: You could set up [all the rigmarole to trigger a refresh on localhost](http://kitsune.readthedocs.org/en/latest/notes.html?highlight=https#about-support-api), which is quite annoying, or you could just set the cookie manually. That's what I did.

r?

### CODE REVIEW

**Comment by mythmon** [comment]
After talking with Kadir, I'm going to rework this to be controlled by a waffle flag so we can throttle it easily.

**Comment by mythmon** [comment]
Reworked to use a waffle flag :point_up: r?

**Comment by rlr** [comment]
travis not happy

**Comment by rlr** [comment]
your changes look good to me :checkered_flag:

**Comment by mythmon** [comment]
Oops, silly JS error.

Also, apparently JS syntax errors will stop the CI build now, so that's cool.

**Pull request merged**
