### PR TITLE
Allow attaching to the web container.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by pmac** [comment]
Based on [the docs](https://docs.docker.com/engine/reference/run/#foreground) it looks like you don't need the stdin line, but the tty one is probably good. I think it's only really needed when you're running as `up`, but when debugging I tend to `docker-compose run` or `docker-compose exec app bash` when I need a shell on the currently running container. How are you using docker when you'd like to have a TTY?

**Comment by pmac** [comment]
There is also a `make runshell` command in the Makefile that gives you a bash shell in the container and has the ports mapped, so you can just `python manage.py runserver` from there and debug as you wish.

**Comment by akatsoulas** [comment]
I am mostly using this to attach to the container when there is debugger breakpoint.

**Comment by pmac** [comment]
Right. So using the `make runshell` to get a real shell in the container is probably best there. But if these changes help you then I'm fine with merging them.

**Comment by akatsoulas** [comment]
Thanks for reviewing!

**Pull request closed without merging**
