### PR TITLE
Responsive product page

### PR DESCRIPTION
**Pull request by kkellydesign**
Three-column responsive math fixed on main landing page. Button is centered.
https://github.com/mozilla/kitsune/issues/3640

Screen Shot 2019-05-20 at 11 16 42 AM

Responsive wrapping fixed on product page: 

Screen Shot 2019-05-20 at 11 22 37 AM

The header has been made responsive on the product page, which solves this issue:
https://github.com/mozilla/kitsune/issues/3645
Screen Shot 2019-05-20 at 11 28 48 AM

The responsive header also addresses this issue (somewhat) in other languages:
https://github.com/mozilla/kitsune/issues/3626

Screen Shot 2019-05-20 at 11 41 36 AM

When only one Contact box is displayed on the product page, it's now centered.
Screen Shot 2019-05-20 at 12 51 24 PM

### CODE REVIEW

**Comment by akatsoulas** [comment]
@kkellydesign probably this PR needs a rebase against the firefox-accounts-integration branch

**Comment by kkellydesign** [comment]
Comments in https://github.com/mozilla/kitsune/issues/3626 reference code in this PR as well. 

Also https://github.com/mozilla/kitsune/issues/3654

**Comment by kkellydesign** [comment]
@akatsoulas I just updated the branch – we should be all set here. Thanks.

**Comment by akatsoulas** [comment]
Closing this in favor of #3664. It includes exactly the same changes. I just cherry-picked the missing commits.

**Pull request closed without merging**
