### PR TITLE
[Bug 1177441]  [Kb] Text missing in mobile site

### PR DESCRIPTION
**Pull request by orvi2014**

### CODE REVIEW

**Comment by pollti** [comment]
Hi :) it would be helpful if you can use square brackets for the bug numer (`[Bug 1177441]`) in the title of PR's, because some tools can read the format `[Bug 1177441] [Kb] Text missing in mobile site`.

**Comment by orvi2014** [comment]
Hi pollti, I change the title .Is it okay now? Let me know if any further change needed.

**Comment by pollti** [comment]
Yes, looks good. Thank you very much! :+1:

**Comment by mythmon** [comment]
Looks good, thank you!

**Pull request merged**
