### PR TITLE
Fix group profile page

### PR DESCRIPTION
**Pull request by smithellis**
The Group Profile page was severely ugly/broken. I have triaged it to a usable state.

### CODE REVIEW

**Comment by kelimuttu** [comment]
Ooh, this is amazing. Thanks for working on this, Smith!

**Review by escattone — CHANGES_REQUESTED** [review]
Thanks for updates @smithellis. Several new observations:
- It appears that we've lost the functionality to add new members?
- I'm not sure we need the `Edit group in admin` button, since I think we can do everything on the page that we could do in the group profile admin? However, if we'd prefer to keep it, since it's currently available, it seems like it should be moved out of the group profile description section, and up into the top area? I also prefer the text `Edit in admin` instead of`Edit group in admin`, just because it shorter.
- Some of the buttons seem too big to me, because of the text. What do you think of shortening `Change Group Avatar` and `Delete Group Avatar` to just `Change Avatar` and `Delete Avatar`?
- When removing members/leaders, the text on the confirmation page is within an `h1` tag, which looks really over-sized to me.

image

image

**Comment by akatsoulas** [comment]
@smithellis is this PR still active and relevant?

**Comment by akatsoulas** [comment]
bumping this

**Comment by akatsoulas** [comment]
Closing this as stale. Please re-open if there's an update

**Pull request closed without merging**
