### PR TITLE
Add tests that were missing from DRF fix

### PR DESCRIPTION
**Pull request by mythmon**
I forgot to commit these files in #2712. They would have caught the problem that PR solved, so they are probably good to have.

### CODE REVIEW

**Comment by mythmon** [comment]
r?

**Comment by rehandalal** [comment]
no travis?

**Comment by mythmon** [comment]
Weird. I'll try and kick Travis.

**Comment by mythmon** [comment]
Travis passed now.

**Comment by rehandalal** [comment]
yay! code looks good. r+

**Pull request merged**
