### PR TITLE
Setup Django's SecurityMiddleware

### PR DESCRIPTION
**Pull request by pmac**
* Exempt /healthz and /readiness URLs from HTTPS redirect
* Remove WSGI HTTPS=on hack
* Remove old commonware security middlewares

### CODE REVIEW

**Comment by metadave** [comment]
@glogiotatidis would you like me to add the following to K8s automation?

- `SECURE_HSTS_SECONDS`
- `SECURE_BROWSER_XSS_FILTER`
- `SECURE_CONTENT_TYPE_NOSNIFF`
- `SECURE_SSL_REDIRECT`

**Comment by glogiotatidis** [comment]
> @glogiotatidis would you like me to add the following to the K8s deployment automation?
> 
>     SECURE_HSTS_SECONDS
>     SECURE_BROWSER_XSS_FILTER
>     SECURE_CONTENT_TYPE_NOSNIFF
>     SECURE_SSL_REDIRECT

Yes please.  It should be
 - `0`
 - `True`
 - `True`
 - `True`

Thanks!

**Comment by pmac** [comment]
Those are all the current defaults btw. Being explicit is good, but just FYI it should all work out of the box w/o changes.

**Comment by glogiotatidis** [comment]
> Those are all the current defaults btw. Being explicit is good, but just FYI it should all work out of the box w/o changes.

Good point and agree, my late day brain was overthinking this. thanks!

**Comment by glogiotatidis** [comment]
Thanks!

**Pull request merged**
