### PR TITLE
Update db_strings.py

### PR DESCRIPTION
**Pull request by yfdyh000**
Update WI-FI to Wi-Fi

### CODE REVIEW

**Comment by willkg** [comment]
These strings come from the database and that file you edited gets auto generated. You'll need to make the changes in SUMO itself.

**Comment by yfdyh000** [comment]
How / Who to edit the strings?

**Comment by mythmon** [comment]
This particular string came from a Topic name. The best way to get this changed would be to post about it on [the SUMO contributors forum](https://support.mozilla.org/forums/contributors).

**Comment by yfdyh000** [comment]
Submitted to https://bugzilla.mozilla.org/show_bug.cgi?id=1155698

**Pull request closed without merging**
