### PR TITLE
Update banner copy.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by wsmwk** [comment]
@akatsoulas Thanks.  I'm not sure replacing "Firefox with "other Mozilla products" address the [issue](https://github.com/mozilla/sumo/issues/1034) because the point of the banner is two fold a) inform people that this discussion location is for the **article**, not for suppoort.

It probably requires some discussion/thought to relace the entire sentence? 

Maybe replace 

**This forum is a discussion about improving the "Installing Thunderbird on Windows" article.
If you need help with Firefox, please [ask a question](https://support.mozilla.org/en-US/questions/new).**

with a shorter and simpler, but broader revision

**This forum is about improving the article "Installing Thunderbird on Windows".
If you are here to get help, please [click here ask a question](https://support.mozilla.org/en-US/questions/new).**

**Comment by akatsoulas** [comment]
thanks @wsmwk. Looping in @abbyparise

**Comment by abbyparise** [comment]
Agree with @wsmwk that we can rewrite to be simpler! This is an opportunity to align with the messaging that's on the Ask a Question page. 

How about...

This forum is about improving the article "Installing Thunderbird on Windows".
If you need product support, please [ask a question](https://support.mozilla.org/en-US/questions/new).

**Comment by wsmwk** [comment]
I like @abbyparise's suggestion

**Comment by akatsoulas** [comment]
Thank you @wsmwk and @abbyparise. Filed PR #5147

**Pull request merged**
