### PR TITLE
[Bug 1210975] Document.related_documents may be blank.

### PR DESCRIPTION
**Pull request by mythmon**
I couldn't figure out how to write a failing test case for this. Any ideas? @willkg ?

r?

### CODE REVIEW

**Comment by willkg** [comment]
I didn't test this, but it looks right to me. Essentially, it's like a 10 character change with an accompanying migration that shouldn't have any db-related effects. blank is specifically validation-related. So everything seems right here to me.

r_plus

**Comment by willkg** [comment]
To answer the question, you can write tests for the admin. It's like writing any other test for a form. I think you'd have to write the post-data by hand since you're writing post-data that omits a form element. I don't usually write admin tests because my admin stuff is usually limited to just me.

@Osmose probably has better thoughts than I do on this.

**Comment by mythmon** [comment]
It seems really weird to me that the models validate things differently than the admin form. I don't really want to get into testing the admin forms, so I'm going to leave this without test.

**Comment by Osmose** [comment]
> I don't really want to get into testing the admin forms

Straight wisdom

**Pull request merged**
