### PR TITLE
Upgrade Django to 1.8.11

### PR DESCRIPTION
**Pull request by mythmon**
The changes between 1.8.9 and 1.8.11 are minor, so this shouldn't be any problem. If CI passes, I expect we are done here.

r?

### CODE REVIEW

**Comment by safwanrahman** [comment]
Maybe 1.8.12 is underway! can we wait till that be in pypi?
https://docs.djangoproject.com/es/1.9/releases/1.8.12/

**Comment by sander120786** [comment]
Sorry
Go

-----Исходное сообщение-----
От: "Mike Cooper" <notifications@github.com>
Отправлено: ‎08.‎03.‎2016 6:44
Кому: "mozilla/kitsune" <kitsune@noreply.github.com>
Тема: [kitsune] Upgrade Django to 1.8.11 (#2809)

The changes between 1.8.9 and 1.8.11 are minor, so this shouldn't be any problem. If CI passes, I expect we are done here.
r?



You can view, comment on, or merge this pull request online at:
  https://github.com/mozilla/kitsune/pull/2809
Commit Summary
Upgrade Django to 1.8.11 
File Changes
M requirements/default.txt (4) 
Patch Links:
https://github.com/mozilla/kitsune/pull/2809.patch 
https://github.com/mozilla/kitsune/pull/2809.diff

**Comment by sander120786** [comment]
Go home ... I sleep


-----Исходное сообщение-----
От: "Mike Cooper" <notifications@github.com>
Отправлено: ‎08.‎03.‎2016 6:44
Кому: "mozilla/kitsune" <kitsune@noreply.github.com>
Тема: [kitsune] Upgrade Django to 1.8.11 (#2809)

The changes between 1.8.9 and 1.8.11 are minor, so this shouldn't be any problem. If CI passes, I expect we are done here.
r?



You can view, comment on, or merge this pull request online at:
  https://github.com/mozilla/kitsune/pull/2809
Commit Summary
Upgrade Django to 1.8.11 
File Changes
M requirements/default.txt (4) 
Patch Links:
https://github.com/mozilla/kitsune/pull/2809.patch 
https://github.com/mozilla/kitsune/pull/2809.diff

**Comment by mythmon** [comment]
Waiting probably isn't a good idea, since this is a very simple change, and includes the upgrade to 1.8.10, which is a security update.

**Comment by safwanrahman** [comment]
Cool! As travis passed, it should get r+
:+1:

**Comment by mythmon** [comment]
I agree. Thanks for looking at this

**Pull request merged**
