### PR TITLE
[Bug 903483] Remove Camino support link from AAQ

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
r?

**Comment by glogiotatidis** [comment]
Thanks for the PR. Due to ongoing discussions about the future of the platform we'll avoid working on any pull requests not directly related to security or maintenance. I've marked this pull request as "Platform Decision Pending" to flag it for later review.

**Comment by MikkCZ** [comment]
@glogiotatidis can we merge this? Should be very easy to review.

**Comment by glogiotatidis** [comment]
Closing PR since development has been halted. Thanks your contribution.

**Pull request closed without merging**
