### PR TITLE
squash DB migrations

### PR DESCRIPTION
**Pull request by escattone**
mozilla/sumo#1243

# Notes
- All database migrations in all apps with more than one migration have been squashed into one migration.
- The original migrations remain until all existing databases have been migrated, after which they can be deleted.
- The squashed migrations for the `questions` and `users` apps have had their non-elidable `RunPython` operations manually added after all of the other operations, so I'd recommend reviewing those squashed migrations more carefully.
- While reviewing, please check that I've excluded the right `RunPython` operations (the ones marked with `elidable=True`) and included the right ones as well in the final squashed migration file. In general, I included the `RunPython` operations that created new data and excluded those that adjusted existing data.

# Next Steps
- After all databases have been migrated, we should create a new PR that deletes all of the migration files that have been replaced by the single squashed migration file.
- After that, we should run a `./manage.py migrate --prune` ([the `--prune` option](https://docs.djangoproject.com/en/4.2/ref/django-admin/#cmdoption-migrate-prune) is new in Django 4.1).

### CODE REVIEW

**Review by akatsoulas — COMMENTED** [review]
Have you tried running this on a clean DB? From what I can see this also includes data migrations so I am curious to see how this will go on an empty DB.

**Comment by escattone** [comment]
> Have you tried running this on a clean DB? From what I can see this also includes data migrations so I am curious to see how this will go on an empty DB.

@akatsoulas Yes, here's the output from a run of `./manage.py migrate` using this code on a fresh MySQL instance:
```
kitsune@737c232d8aba:~$ ./manage.py migrate
System check identified some issues:

WARNINGS:
...
Operations to perform:
  Apply all migrations: actstream, admin, announcements, auth, authtoken, contenttypes, customercare, dashboards, flagit, forums, gallery, groups, guardian, inproduct, journal, karma, kbadge, kbforums, kitsune_messages, kpi, notifications, postcrash, product_details, products, questions, search, sessions, sites, sumo, taggit, tidings, upload, users, waffle, wiki
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying actstream.0001_initial... OK
  Applying actstream.0002_remove_action_data... OK
  Applying actstream.0003_add_follow_flag... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying taggit.0001_initial... OK
  Applying products.0001_squashed_0005_auto_20200629_0826... OK
  Applying gallery.0001_squashed_0009_auto_20220107_0617... OK
  Applying wiki.0001_squashed_0013_alter_document_related_documents_and_more... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying announcements.0001_squashed_0006_remove_announcement_group_and_more... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying customercare.0001_squashed_0002_auto_20210716_0556... OK
  Applying dashboards.0001_squashed_0010_auto_20210726_1036... OK
  Applying flagit.0001_squashed_0002_auto_20200629_0826... OK
  Applying guardian.0001_initial... OK
  Applying guardian.0002_generic_permissions_index... OK
  Applying forums.0001_squashed_0004_remove_authority... OK
  Applying groups.0001_squashed_0002_auto_20200629_0826... OK
  Applying inproduct.0001_squashed_0003_alter_redirect_platform_alter_redirect_product_and_more... OK
  Applying journal.0001_initial... OK
  Applying karma.0001_squashed_0002_auto_20200629_0826... OK
  Applying kbadge.0001_squashed_0005_drop_ghost_columns... OK
  Applying kbforums.0001_initial... OK
  Applying kitsune_messages.0001_initial... OK
  Applying kpi.0001_squashed_0002_cohort_retention_models... OK
  Applying notifications.0001_initial... OK
  Applying postcrash.0001_initial... OK
  Applying product_details.0001_initial... OK
  Applying product_details.0002_auto_20151006_1348... OK
  Applying waffle.0001_initial... OK
  Applying questions.0001_squashed_0013_alter_question_is_archived... OK
  Applying search.0001_squashed_0006_auto_20210526_0243... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying sumo.0001_squashed_0002_initial_data... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying taggit.0003_taggeditem_add_unique_index... OK
  Applying taggit.0004_alter_taggeditem_content_type_alter_taggeditem_tag... OK
  Applying taggit.0005_auto_20220424_2025... OK
  Applying tidings.0001_squashed_0002_update_email_size... OK
  Applying upload.0001_squashed_0003_auto_20200629_0826... OK
  Applying users.0001_squashed_0027_profile_zendesk_id... OK
  Applying waffle.0002_auto_20161201_0958... OK
  Applying waffle.0003_update_strings_for_i18n... OK
  Applying waffle.0004_update_everyone_nullbooleanfield... OK
```

**Comment by escattone** [comment]
@akatsoulas The data migrations I kept were the ones that created some initial data (for example, creating some AAQ `QuestionLocale` instances), but maybe we don't need those either? I'd love to drop those too, if you're OK with that? I wonder if that would affect the initial locale development setup?

**Comment by escattone** [comment]
Hm, we may have to keep that sumo app migration that creates the "Bypass Ratelimits" `Permission` instance and its related `sumo.global_permission` `ContentType` .

**Review by akatsoulas — APPROVED** [review]
nice work!

**Pull request merged**
