### PR TITLE
[Bug 1405844] User Registration on mobile fails

### PR DESCRIPTION
**Pull request by safwanrahman**
It should fix the issue. Similar to #2801
@glogiotatidis @pmac r?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Thanks @safwanrahman 

I tried a similar fix yesterday and it didn't work. I now pushed yours to staging (you're using `with context`) which I didn't and it still doesn't work. `csrf` is not included in the POSTed data.

Does this work for you locally?

**Comment by safwanrahman** [comment]
@glogiotatidis Its working locally for me. Can you test this in your local machine? have you restart the server in stage while deploying? template change may not detected without a restart.

**Comment by safwanrahman** [comment]
@glogiotatidis Sorry, its my bad. I thought the AAQ registration flow and normal registration flow were using the same template. Therefore I was testing the registration process only locally.
Looking at the code and workflow, it seems that both are using different template. I have fixed that in the latest commit and tested the AAQ flow locally in mobile view. it seems to be working now.
Moreover, I have added another test that would test the functionality.
r?

**Comment by glogiotatidis** [comment]
Verified working. Thanks @safwanrahman !

**Pull request merged**
