### PR TITLE
"Moderate Forum Content" fits better into the Tools section

### PR DESCRIPTION
**Pull request by philipp-sumo**

### CODE REVIEW

**Comment by akatsoulas** [comment]
@jonichan @jess-cook03 can you take a look at this PR?

**Comment by jess-cook03** [comment]
@akatsoulas I'm confused about this suggested change. This has not been vetted by Joni or myself. Is there a bugzilla issue with more details?

**Comment by akatsoulas** [comment]
I am not aware of any. That's why I pinged you and Joni, so that you can provide feedback on this change. I will link this PR to an issue and we can discuss this there.

**Comment by akatsoulas** [comment]
Closing in favor of #4397. It's the same PR with the conflict resolved.

**Pull request closed without merging**
