### PR TITLE
[bug 1172603] [bug 1172604] Search on mobile product pages

### PR DESCRIPTION
**Pull request by rehandalal**
r?

### CODE REVIEW

**Comment by mythmon** [comment]
Not sure why Travis failed. I restarted the job.

**Comment by mythmon** [comment]
I played with this locally. It looks good, though when the search results are short seeing the bottom of the page is weird. I think that is true for the entire mobile site when the content is too short though.

There isn't any feedback when your search gave back no results compared to when it is just pending. Having a loading spinner and/or a "Your search had no results" message would be nice.

**Comment by rehandalal** [comment]
updated to include "no results" message ^

**Comment by rehandalal** [comment]
bottom of the page issue is fixed by #2572

**Comment by mythmon** [comment]
Looks good. r+ once Travis like it.

**Comment by rehandalal** [comment]
oops! that should fix it ^

**Comment by rehandalal** [comment]
travis is happy, merging!

**Pull request merged**
