### PR TITLE
Make TravisCI retry setup and install steps

### PR DESCRIPTION
**Pull request by mythmon**
@safwanrahman r?

### CODE REVIEW

**Comment by mythmon** [comment]
@homu delegate=safwanrahman

**Comment by safwanrahman** [comment]
seems to be late. but it looks good. r+ late

**Comment by mythmon** [comment]
Ignore the noise of closing and deleting. GitHub was having some trouble. You can approve this by telling homu r+ (since you have delegate permission).

**Comment by mythmon** [comment]
@homu r=safwanrahman

**Comment by mythmon** [comment]
@homu retry

**Comment by safwanrahman** [comment]
@homu retry

**Comment by safwanrahman** [comment]
@homu retry

**Comment by safwanrahman** [comment]
@homu retry

**Comment by safwanrahman** [comment]
@homu retry

**Comment by safwanrahman** [comment]
@homu r+

**Pull request merged**
