### PR TITLE
[Bug 1241666] Add CSAT charts to dashboards

### PR DESCRIPTION
**Pull request by brittanystoroz**
Adds CSAT charts to KPI dashboard and community metrics page. You'll have to have some data locally in order for the graphs to load.

### CODE REVIEW

**Comment by rehandalal** [comment]
test failure looked unrelated... restarted.

**Comment by rehandalal** [comment]
@brittanystoroz could you check out these conflicts?

**Comment by safwanrahman** [comment]
The template directory has been changed. Please rebase

**Comment by brittanystoroz** [comment]
@rdalal Rebased and conflicts are gone :)

**Comment by rehandalal** [comment]
sweet r+

**Pull request merged**
