### PR TITLE
 [Bug 1205093] Show Ready for L10n in the KB dashboard based on the latest normal or major revision

### PR DESCRIPTION
**Pull request by MikkCZ**
Waiting for Joni info about the minor revisions correct behavior.

### CODE REVIEW

**Comment by safwanrahman** [comment]
The Dashboard part is so critical that, without a full time commited dev, I would rather not make any changes there. Because it is very critical and raises a lot of regression in the past.
Your work is awesome, but I think its better to keep the dashboard as it is till we dont get any full time dev.

**Comment by MikkCZ** [comment]
OK. Let's do not merge this until we have a full time developer or we know the future direction of the platform development.

I will anyway update info in this PR once I get the info from Jonii and commit any necessary changes if I am able to do them, so this is not stuck somewhere in the middle.

**Comment by MikkCZ** [comment]
Looking at my other PR, I will write some tests for this, too...

**Comment by MikkCZ** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1205093#c7 the behavior I expected is correct. So it's time to make some tests for this.

**Comment by glogiotatidis** [comment]
Thanks for the PR. Due to ongoing discussions about the future of the platform we'll avoid working on any pull requests not directly related to security or maintenance. I've marked this pull request as "Platform Decision Pending" to flag it for later review.

**Comment by glogiotatidis** [comment]
Closing PR since development has been halted. Thanks your contribution.

**Pull request closed without merging**
