### PR TITLE
[Bug 1095972] Change link in revision ready e-mail

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by safwanrahman** [comment]
Have you tested this in locale?

**Comment by MikkCZ** [comment]
I ran the tests, but forgot to `git add` after the last change. :(

**Comment by MikkCZ** [comment]
The failure does not seem to be related to me. Or is it?

**Comment by safwanrahman** [comment]
Have you tested this in local that the email is containing the expected link?

**Comment by MikkCZ** [comment]
Yes, I checked it is being printed to the output as [mentioned in the documentation](https://kitsune.readthedocs.io/en/latest/email.html), I haven't set up actual sending of the emails, but in the terminal output the link is as expected.

**Comment by glogiotatidis** [comment]
Thanks for the PR. Due to ongoing discussions about the future of the platform we'll avoid working on any pull requests not directly related to security or maintenance. I've marked this pull request as "Platform Decision Pending" to flag it for later review.

**Comment by glogiotatidis** [comment]
Closing PR since development has been halted. Thanks your contribution.

**Pull request closed without merging**
