### PR TITLE
add phishing banner

### PR DESCRIPTION
**Pull request by LeoMcA**
Screenshot_2020-06-16 Firefox Support Forum Mozilla Support - 127 0 0 1

Appears across:
`/questions/<product>`
`/questions/<question_id>`
`/questions/new*`

### CODE REVIEW

**Comment by LeoMcA** [comment]
Reduced the vertical padding slightly:

Screenshot_2020-06-16 Ask a Question Mozilla Support - 127 0 0 1(1)

**Comment by LeoMcA** [comment]
Button colours updated:

Screenshot_2020-06-16 All Products Support Forum Mozilla Support - 127 0 0 1

**Comment by LeoMcA** [comment]
Updated fonts/icon size:

Screen Shot 2020-06-16 at 14 28 43

**Comment by AliceWyman** [comment]
A bug report, https://bugzilla.mozilla.org/show_bug.cgi?id=1647741 has been filed asking to change the banner and email message, to clarify that Mozilla will not ask you to call a number or visit a non-Mozilla site **for help with Mozilla products**.

**Pull request merged**
