### PR TITLE
Add .idea to .gitignore

### PR DESCRIPTION
**Pull request by MikkCZ**
I am testing PyCharm and it looks pretty good. Let's make sure no IDE project files are committed.

### CODE REVIEW

**Comment by safwanrahman** [comment]
Kitsune Should be Platform Independent and also IDE. Its not wise to add any specific IDE file into git ignore.

**Comment by MikkCZ** [comment]
For the same reason I think no IDE files should get into the master ever, and .gitignore is the way to avoid it.

**Comment by glogiotatidis** [comment]
SInce we have no other platform / ide specifics on .gitignore I suggest that we keep it this way. But I agree that we should protect master from accidental additions. @MikkCZ have you tried putting files to our own project specific gitignore at `$GIT_DIR/info/exclude` ? Does this work for you?

**Comment by MikkCZ** [comment]
Oh, that works too. :)

**Pull request closed without merging**
