### PR TITLE
[Bug 1271132] Recover and update l10n scripts

### PR DESCRIPTION
**Pull request by MikkCZ**
Other scripts are not used nor mentioned anywhere.

### CODE REVIEW

**Comment by MikkCZ** [comment]
r?

**Comment by glogiotatidis** [comment]
Thanks for the PR. Due to ongoing discussions about the future of the platform we'll avoid working on any pull requests not directly related to security or maintenance. I've marked this pull request as "Platform Decision Pending" to flag it for later review.

**Comment by glogiotatidis** [comment]
Closing PR since development has been halted. Thanks your contribution.

**Comment by MikkCZ** [comment]
@glogiotatidis Would you make use of these script during l10n extract and deploy, to compile and test the localization files?

**Comment by glogiotatidis** [comment]
I re-open to take a look when avail

**Pull request closed without merging**
