### PR TITLE
Make "said" text localizable when quoting

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
My local venv gets broken. Have to fix it and check this.

**Comment by MikkCZ** [comment]
Should work as expected.

**Comment by safwanrahman** [comment]
Have you tested it? let me know, so easy for review.
Thanks

**Comment by MikkCZ** [comment]
I was unable to file any question on local installation fot some reason, so I saved html file with injected JS files. Would be great if can test on real, but not sure what's missing in the local instance.

**Comment by MikkCZ** [comment]
@glogiotatidis r?

**Comment by MikkCZ** [comment]
Finally managed to test locally (article discussion + manually pasting https://support.cdn.mozilla.net/static/jsi18n/cs/djangojs.538269379a03.js content with manually added string into console) and it works.

@glogiotatidis r?

**Comment by glogiotatidis** [comment]
Thanks @MikkCZ

**Pull request merged**
