### PR TITLE
[bug 1136188] Tower extracts strings from nunjucks

### PR DESCRIPTION
**Pull request by rehandalal**
r?

### CODE REVIEW

**Comment by mythmon** [comment]
I don't see any new strings in javascript.pot (or any other .pot file for that matter) when I run `./manage.py extract` with this patch. Did I do something wrong?

**Comment by rehandalal** [comment]
weird... i see them... 
https://pastebin.mozilla.org/8851954

**Comment by mythmon** [comment]
Doh. I was using the wrong branch when I was testing this. \*fail\*.

This is awesome, thanks! I think this also fixes [bug 1180783](https://bugzilla.mozilla.org/show_bug.cgi?id=1180783), at least from what I saw in the svn diff. Do you agree?

**Comment by rehandalal** [comment]
yeah it also fixes that bug!

**Pull request merged**
