### PR TITLE
[Bug 1169912] Add number of days since last activity to the user profile

### PR DESCRIPTION
**Pull request by MikkCZ**
Adds the number of days since last user activity to his/her profile page into the Contributions section.

### CODE REVIEW

**Comment by MikkCZ** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
Hi @MikkCZ. Thank you for your PR. In case you're not aware Kitsune is being actively worked on to get migrated to AWS. The `master` branch has diverged from what's live now in SCL3. 

That means that we're only accepting AWS related PRs against `master` and only security and product support PRs against `legacy`. 

Since you already spend some time on this and your other PRs will review and if not too complicated I'll merge. This is though an exception to the rule and we will not spend time develop features. 

If you have questions feel free to reach out. Thanks!

**Comment by MikkCZ** [comment]
Thanks for info. The patches are not critical, so you can keep them for later after the migration is finished.

**Comment by bessix05** [comment]
> Duplicate of #

Stop admit

**Comment by andrewhager9** [comment]
Are you able to help me with this

**Review by andrewhager9 — APPROVED** [review]
How do I run this

**Comment by MikkCZ** [comment]
I haven't worked on Kitsune for a very long time, however as I see the patch, it's rather easy and should still be relevant.

As for setting up the development environment, probably check the project README, or maybe @LeoMcA or @akatsoulas can help you with this.

**Comment by MikkCZ** [comment]
This PR is stale for too long, so I am closing this. The history should be preserved, so if anyone want's to update it or use as inspiration, feel free to.

**Review by kenzierose59 — COMMENTED** [review]
@

**Pull request closed without merging**
