### PR TITLE
Filter by product in topic navigation.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Review by escattone — CHANGES_REQUESTED** [review]
I'm getting an error when I select one of the products in the product dropdown, and it's because the `Topic.get_absolute_url()` method is still designed for the old world of a topic always existing under a single product.

image

Otherwise, this looks good to me.

**Comment by akatsoulas** [comment]
Thanks for the prompt review. Since this code is looking good, I am merging this and I am going to tackle the error in https://github.com/mozilla/sumo/issues/1917 which affects all articles.

**Comment by 2000400** [comment]
```

```

**Review by 2000400 — CHANGES_REQUESTED** [review]
[]()[]()

**Pull request merged**
