### PR TITLE
Update django-adminplus to latest version on pypi.

### PR DESCRIPTION
**Pull request by rlr**
r?

### CODE REVIEW

**Comment by mythmon** [comment]
I think you got some `+`s in there.

**Comment by rlr** [comment]
lmao. effing copy paste fail.

**Comment by rlr** [comment]
whew. fixed.

**Comment by rlr** [comment]
Commits:
https://github.com/jsocol/django-adminplus/compare/90c6aca7a9c18f90af20d111141b1670ef6af206...v0.3

There is nothing of interest and this wasn't an issue for me for django 1.7 at all but I figured I'd put us on the latest and on pypi.

**Pull request merged**
