### PR TITLE
Add proper variable for static url in email base template

### PR DESCRIPTION
**Pull request by pmac**
Fix broken image in SUMO emails.

Fix bug 1262192

### CODE REVIEW

**Comment by pmac** [comment]
I saw that the header image in emails I was getting was broken and found the old bug filed about it. I think this should fix it. The image in the email needs updating for branding purposes however.

**Comment by jpetto** [comment]
Yeah, if "Support" is part of the image, we should re-render it using Zilla Slab.

**Comment by pmac** [comment]
may need your image manipulation expertise on that. I can give it a shot if you're too busy.

**Comment by jpetto** [comment]
On it. 😀

**Comment by jpetto** [comment]
Here ya go!

mozilla-support

**Comment by jpetto** [comment]
And an alternate, just in case:

mozilla-support-alt

**Comment by pmac** [comment]
@jpetto based on https://mozilla.design/mlogo I thought it was supposed to be the latter, but I don't really care. Perhaps we should ask Patrick or Madalina?

**Comment by pmac** [comment]
And I still have to fix my failing test.

**Comment by pmac** [comment]
Also thanks for those images!!! 🥇

**Comment by jpetto** [comment]
Ah, yes, I believe you are right - let's use the second logo posted, the one with the black box around the wordmark.

**Comment by pmac** [comment]
Tests passed! (db gone away problem again)

**Pull request merged**
