### PR TITLE
Fix cron command for ES reindex.

### PR DESCRIPTION
**Pull request by akatsoulas**
Fixes issue #3620

### CODE REVIEW

**Comment by pmac** [comment]
This seems like a good change that will fix the scheduled reindex task, but I don't think it fixes #3620 which I thought referred to the command being broken on the es_upgrade branch. I could be wrong about that though.

**Comment by akatsoulas** [comment]
I thought that the indexing command was fixed through #3575 . I tested locally this patch and it looked like the indexing run normally.  Is there another issue related to the indexing?

**Comment by pmac** [comment]
It's broken on the `es_upgrade` branch, not `master`, on which this PR is based. So upgrading to a new version of the ElasticSearch server and moving to `elasticsearch_dsl` is what is blocked, not the Django upgrade.

**Comment by akatsoulas** [comment]
Thanks for the explanation! This PR though should fix the cron command that is failing in master.

**Pull request merged**
