### PR TITLE
Remove schematic migrations.

### PR DESCRIPTION
**Pull request by mythmon**
We kept these around for a little while because we used them to bootstrap South. I don't think we need these anymore though.

:boom: r?

### CODE REVIEW

**Comment by rehandalal** [comment]
yay!

**Comment by rehandalal** [comment]
one failure looks related

**Comment by rehandalal** [comment]
i think you just got to remove the test that checks for the migration folder.

**Comment by mythmon** [comment]
Removed the tests. This will still fail because of that error with the AAQ stuff. I'll rebase this once #2616 lands.

**Comment by mythmon** [comment]
^ rebased on top of master with #2616's changes.

**Comment by rehandalal** [comment]
r+

**Pull request merged**
