### PR TITLE
[#3905] Adding document for ES7

### PR DESCRIPTION
**Pull request by safwanrahman**
Firs iteration to take the branch `es_upgrade`
#3905

### CODE REVIEW

**Comment by safwanrahman** [comment]
@johngian thoughts?

**Comment by safwanrahman** [comment]
@akatsoulas I have updated the document as per we have discussed using multi fields. Let me know if you have any questions.

**Comment by 1298330** [comment]
Didn't make contact to Mozilla)Kitsune #3905 to add documents to ES7 don't
know Safwan Rahman commits are sending documents  from mozzila/Kitsune
disconnect return documents stolen from my phone.  Please find anything
else you need me to diiscuss without keeping the list of hack my phone
number and  private Data email addresses disrespectfully disruptive.
Thank you,
Eugene B Pacifico

1230984567

**Comment by akatsoulas** [comment]
Closing in favor of #4006

**Pull request closed without merging**
