### PR TITLE
Fix Bug 1380708 implement static tabzilla

### PR DESCRIPTION
**Pull request by bensternthal**
Removed commented out test code.

### CODE REVIEW

**Comment by bensternthal** [comment]
@glogiotatidis at your leisure but i wanted to get this in your backlog. See referenced bug for context.

**Comment by MikkCZ** [comment]
[Mozilla infobar](https://github.com/mozilla/mozilla-infobar) is not part of this change?

**Comment by bensternthal** [comment]
This pr is specific to removing the old style tabzilla.

It's entirely possible to add info bar stuff to kitsune if it works/is required but it should be tracked and implemented separately.

**Comment by glogiotatidis** [comment]
Merged here https://github.com/mozilla/kitsune/commit/a0e287dbe506ff92718c96c3cf5ad70ebff53430

Thanks 🍺

**Pull request closed without merging**
