### PR TITLE
[Bug 611641] Only L10N Needed Locals should be shown as target local

### PR DESCRIPTION
**Pull request by safwanrahman**
Hope this patch fix the Issue! :)

### CODE REVIEW

**Comment by safwanrahman** [comment]
@mythmon @rlr @rehandalal Its working as expected.
r?

**Comment by safwanrahman** [comment]
@rlr @mythmon r?

**Comment by rlr** [comment]
Looks like you have covered all the comments. I'll do a quick test locally and merge if it's good. Thanks!

**Comment by rlr** [comment]
works great r+!

**Comment by rlr** [comment]
3380c8f675d68997c9116fb17179f0046d997beb [Bug 611641] Only L10N Needed Locals should be shown as target local

**Pull request closed without merging**
