### PR TITLE
[fix bug 1259953] Wrap GA in DNT conditional.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Respect user's DNT flag.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@safwanrahman @MikkCZ r?

**Comment by MikkCZ** [comment]
Pulled, tested and works. Could we add the JS test you linked in https://bugzilla.mozilla.org/show_bug.cgi?id=1259953#c4 too?

**Comment by glogiotatidis** [comment]
> Pulled, tested and works. Could we add the JS test you linked in https://bugzilla.mozilla.org/show_bug.cgi?id=1259953#c4 too?

Good point. I added a note that this is direct copy. Since we're not diverging i'll use this as a library and skip adding tests.

**Comment by MikkCZ** [comment]
:+1: r+

**Comment by safwanrahman** [comment]
It seems like, the ``dnt-helper.js`` will not load in mobile site and minimal view. Can you please check @glogiotatidis

**Comment by safwanrahman** [comment]
Also test fail seems relative. The linter style is not matched. You can test it locally. the instruction is  [here](http://kitsune.readthedocs.io/en/latest/hacking_howto.html#install-linting-tools)

**Comment by glogiotatidis** [comment]
> Also test fail seems relative. The linter style is not matched. You can test it locally. the instruction is here

FYI Added proper editor config for JS https://github.com/mozilla/kitsune/commit/1db1d9ece8eda1eb6d63a362d348cb880542c74c

**Comment by glogiotatidis** [comment]
it should be fine now, @safwanrahman ?

**Comment by safwanrahman** [comment]
Looks Good @glogiotatidis 
r+ :+1:

**Comment by safwanrahman** [comment]
Lets test it into stage first before sending to production

**Pull request merged**
